language: node_js
node_js:
  - "14.15"
branches:
  only:
    - main
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  on:
    all_branches: true
  token: "1//0g64YrQuwyKEYCgYIARAAGBASNwF-L9IrifLMqdUKJwjwlh9XCSIZgjOYk-NY32gmecKdCSsDmJ2IA5f1fBhwdeoP-JLY4d7L7jw"
    
